
package com.shrikantchine.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrderDetailsServiceImplService", targetNamespace = "http://ws.shrikantchine.com/", wsdlLocation = "http://localhost:7004/services/orders?wsdl")
public class OrderDetailsServiceImplService
    extends Service
{

    private final static URL ORDERDETAILSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORDERDETAILSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ORDERDETAILSSERVICEIMPLSERVICE_QNAME = new QName("http://ws.shrikantchine.com/", "OrderDetailsServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7004/services/orders?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERDETAILSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ORDERDETAILSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public OrderDetailsServiceImplService() {
        super(__getWsdlLocation(), ORDERDETAILSSERVICEIMPLSERVICE_QNAME);
    }

    public OrderDetailsServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERDETAILSSERVICEIMPLSERVICE_QNAME, features);
    }

    public OrderDetailsServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ORDERDETAILSSERVICEIMPLSERVICE_QNAME);
    }

    public OrderDetailsServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERDETAILSSERVICEIMPLSERVICE_QNAME, features);
    }

    public OrderDetailsServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderDetailsServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrderDetailsService
     */
    @WebEndpoint(name = "OrderDetailsServiceImplPort")
    public OrderDetailsService getOrderDetailsServiceImplPort() {
        return super.getPort(new QName("http://ws.shrikantchine.com/", "OrderDetailsServiceImplPort"), OrderDetailsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderDetailsService
     */
    @WebEndpoint(name = "OrderDetailsServiceImplPort")
    public OrderDetailsService getOrderDetailsServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.shrikantchine.com/", "OrderDetailsServiceImplPort"), OrderDetailsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERDETAILSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ORDERDETAILSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ORDERDETAILSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
